CREATE INDEX idx_restaurants_tasco_poi_id ON restaurants(tasco_poi_id);
CREATE INDEX idx_restaurants_normalized_name ON restaurants(normalized_name);
CREATE INDEX idx_restaurants_status_quality ON restaurants(status, quality_score);
CREATE INDEX idx_branches_restaurant_id ON restaurant_branches(restaurant_id);
CREATE INDEX idx_branches_city_district ON restaurant_branches(city, district);
CREATE INDEX idx_sources_restaurant_id ON sources(restaurant_id);
CREATE INDEX idx_sources_processing_status ON sources(processing_status);
CREATE INDEX idx_sources_content_hash ON sources(content_hash);
CREATE INDEX idx_claims_restaurant_predicate ON claims(restaurant_id, predicate);
CREATE INDEX idx_claims_status ON claims(status);
CREATE INDEX idx_claims_source ON claims(source_id);
CREATE INDEX idx_menu_items_restaurant_id ON menu_items(restaurant_id);
CREATE INDEX idx_menu_items_normalized_name ON menu_items(normalized_name);
CREATE INDEX idx_menu_items_price ON menu_items(price_amount_vnd);
CREATE INDEX idx_menus_restaurant_status ON menus(restaurant_id, status);
CREATE INDEX idx_reviews_restaurant ON reviews(restaurant_id);
CREATE INDEX idx_ingestion_jobs_status ON ingestion_jobs(status);
CREATE INDEX idx_audit_entity ON audit_events(entity_type, entity_id);
